#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
#define BSP_BUTTON_PRESENT                       (1)

#define BSP_BUTTON0_PIN                          (11U)
#define BSP_BUTTON0_PORT                         (gpioPortB)

#define BSP_BUTTON1_PIN                          (9U)
#define BSP_BUTTON1_PORT                         (gpioPortC)

#define BSP_BUTTON_COUNT                         (2U)
#define BSP_BUTTON_INIT                          { { BSP_BUTTON0_PORT, BSP_BUTTON0_PIN }, { BSP_BUTTON1_PORT, BSP_BUTTON1_PIN } }
#define BSP_BUTTON_GPIO_DOUT                     (HAL_GPIO_DOUT_HIGH)
#define BSP_BUTTON_GPIO_MODE                     (HAL_GPIO_MODE_INPUT_PULL)
#define HAL_BUTTON_ENABLE                        { 0, 1 }
#define HAL_BUTTON_COUNT                         (2U)
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                     (HAL_CLK_HFCLK_SOURCE_HFXO)
#define HAL_CLK_LFECLK_SOURCE                    (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFBCLK_SOURCE                    (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFACLK_SOURCE                    (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_HFXO_AUTOSTART                   (HAL_CLK_HFXO_AUTOSTART_NONE)
// [CMU]$

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[CSEN]
// [CSEN]$

// $[DCDC]
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[FEM]
// [FEM]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
#define PORTIO_I2C0_SCL_PIN                      (5U)
#define PORTIO_I2C0_SCL_PORT                     (gpioPortA)
#define PORTIO_I2C0_SCL_LOC                      (4U)

#define PORTIO_I2C0_SDA_PIN                      (4U)
#define PORTIO_I2C0_SDA_PORT                     (gpioPortA)
#define PORTIO_I2C0_SDA_LOC                      (4U)

#define HAL_I2C0_ENABLE                          (1)

#define BSP_I2C0_SDA_PIN                         (4U)
#define BSP_I2C0_SDA_PORT                        (gpioPortA)
#define BSP_I2C0_SDA_LOC                         (4U)

#define BSP_I2C0_SCL_PIN                         (5U)
#define BSP_I2C0_SCL_PORT                        (gpioPortA)
#define BSP_I2C0_SCL_LOC                         (4U)

#define HAL_I2C0_LOW_HIGH_RATIO                  (_I2C_CTRL_CLHR_STANDARD)
#define HAL_I2C0_INIT_ENABLE                     (0)
#define HAL_I2C0_MAX_BUS_FREQ                    (0UL)
#define HAL_I2C0_MASTER                          (0)
// [I2C0]$

// $[I2C1]
#define PORTIO_I2C1_SCL_PIN                      (11U)
#define PORTIO_I2C1_SCL_PORT                     (gpioPortC)
#define PORTIO_I2C1_SCL_LOC                      (19U)

#define PORTIO_I2C1_SDA_PIN                      (10U)
#define PORTIO_I2C1_SDA_PORT                     (gpioPortC)
#define PORTIO_I2C1_SDA_LOC                      (19U)

#define HAL_I2C1_ENABLE                          (1)

#define BSP_I2C1_SDA_PIN                         (10U)
#define BSP_I2C1_SDA_PORT                        (gpioPortC)
#define BSP_I2C1_SDA_LOC                         (19U)

#define BSP_I2C1_SCL_PIN                         (11U)
#define BSP_I2C1_SCL_PORT                        (gpioPortC)
#define BSP_I2C1_SCL_LOC                         (19U)

#define HAL_I2C1_LOW_HIGH_RATIO                  (_I2C_CTRL_CLHR_STANDARD)
#define HAL_I2C1_INIT_ENABLE                     (0)
#define HAL_I2C1_MAX_BUS_FREQ                    (0UL)
#define HAL_I2C1_MASTER                          (0)
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[MODEM]
// [MODEM]$

// $[PA]
#define HAL_PA_ENABLE                            (1)

#define HAL_PA_RAMP                              (10UL)
#define HAL_PA_2P4_LOWPOWER                      (0)
#define HAL_PA_POWER                             (252U)
#define BSP_PA_VOLTAGE                           (3300U)
#define HAL_PA_CURVE_HEADER                       "pa_curves_efr32.h"
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PCNT1]
// [PCNT1]$

// $[PCNT2]
// [PCNT2]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
#define HAL_SERIAL_USART0_ENABLE                 (1)
#define BSP_SERIAL_APP_PORT                      (HAL_SERIAL_PORT_USART0)
#define HAL_SERIAL_LEUART0_ENABLE                (0)
#define BSP_SERIAL_ASSERT_PORT                   (HAL_SERIAL_PORT_USART0)
#define HAL_SERIAL_USART1_ENABLE                 (1)
#define HAL_SERIAL_USART2_ENABLE                 (0)
#define HAL_SERIAL_USART3_ENABLE                 (0)
#define HAL_SERIAL_RXWAKE_ENABLE                 (0)
#define HAL_SERIAL_IDLE_WAKE_ENABLE              (1)
#define BSP_SERIAL_APP_RX_PIN                    (0U)
#define BSP_SERIAL_APP_RX_PORT                   (gpioPortA)
#define BSP_SERIAL_APP_RX_LOC                    (31U)

#define BSP_SERIAL_APP_TX_PIN                    (1U)
#define BSP_SERIAL_APP_TX_PORT                   (gpioPortA)
#define BSP_SERIAL_APP_TX_LOC                    (1U)

#define HAL_SERIAL_APP_RX_QUEUE_SIZE             (128UL)
#define HAL_SERIAL_APP_BAUD_RATE                 (9600UL)
#define HAL_SERIAL_APP_RXSTOP                    (16UL)
#define HAL_SERIAL_APP_RXSTART                   (16UL)
#define HAL_SERIAL_APP_TX_QUEUE_SIZE             (128UL)
#define HAL_SERIAL_APP_FLOW_CONTROL              (HAL_USART_FLOW_CONTROL_NONE)
#define BSP_SERIAL_ASSERT_RX_PIN                 (0U)
#define BSP_SERIAL_ASSERT_RX_PORT                (gpioPortA)
#define BSP_SERIAL_ASSERT_RX_LOC                 (31U)

#define BSP_SERIAL_ASSERT_TX_PIN                 (1U)
#define BSP_SERIAL_ASSERT_TX_PORT                (gpioPortA)
#define BSP_SERIAL_ASSERT_TX_LOC                 (1U)

#define HAL_SERIAL_ASSERT_RX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_ASSERT_BAUD_RATE              (9600UL)
#define HAL_SERIAL_ASSERT_RXSTOP                 (16UL)
#define HAL_SERIAL_ASSERT_RXSTART                (16UL)
#define HAL_SERIAL_ASSERT_TX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_ASSERT_FLOW_CONTROL           (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_RX_PIN                     (0U)
#define PORTIO_USART0_RX_PORT                    (gpioPortA)
#define PORTIO_USART0_RX_LOC                     (31U)

#define PORTIO_USART0_TX_PIN                     (1U)
#define PORTIO_USART0_TX_PORT                    (gpioPortA)
#define PORTIO_USART0_TX_LOC                     (1U)

#define HAL_USART0_ENABLE                        (1)

#define BSP_USART0_RX_PIN                        (0U)
#define BSP_USART0_RX_PORT                       (gpioPortA)
#define BSP_USART0_RX_LOC                        (31U)

#define BSP_USART0_TX_PIN                        (1U)
#define BSP_USART0_TX_PORT                       (gpioPortA)
#define BSP_USART0_TX_LOC                        (1U)

#define HAL_USART0_RX_QUEUE_SIZE                 (128UL)
#define HAL_USART0_BAUD_RATE                     (9600UL)
#define HAL_USART0_RXSTOP                        (16UL)
#define HAL_USART0_RXSTART                       (16UL)
#define HAL_USART0_TX_QUEUE_SIZE                 (128UL)
#define HAL_USART0_FLOW_CONTROL                  (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_RX_PIN                     (7U)
#define PORTIO_USART1_RX_PORT                    (gpioPortC)
#define PORTIO_USART1_RX_LOC                     (11U)

#define PORTIO_USART1_TX_PIN                     (6U)
#define PORTIO_USART1_TX_PORT                    (gpioPortC)
#define PORTIO_USART1_TX_LOC                     (11U)

#define HAL_USART1_ENABLE                        (1)

#define BSP_USART1_RX_PIN                        (7U)
#define BSP_USART1_RX_PORT                       (gpioPortC)
#define BSP_USART1_RX_LOC                        (11U)

#define BSP_USART1_TX_PIN                        (6U)
#define BSP_USART1_TX_PORT                       (gpioPortC)
#define BSP_USART1_TX_LOC                        (11U)

#define HAL_USART1_RX_QUEUE_SIZE                 (128UL)
#define HAL_USART1_BAUD_RATE                     (9600UL)
#define HAL_USART1_RXSTOP                        (16UL)
#define HAL_USART1_RXSTART                       (16UL)
#define HAL_USART1_TX_QUEUE_SIZE                 (128UL)
#define HAL_USART1_FLOW_CONTROL                  (HAL_USART_FLOW_CONTROL_NONE)
// [USART1]$

// $[USART2]
// [USART2]$

// $[USART3]
// [USART3]$

// $[VCOM]
#define HAL_VCOM_ENABLE                          (1)

// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[VUART]
// [VUART]$

// $[WDOG]
#define HAL_WDOG_ENABLE                          (1)

// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

// $[WTIMER1]
// [WTIMER1]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

